// @ts-nocheck
import * as __fd_glob_63 from "../content/docs/(root)/roadmap.mdx?collection=docs"
import * as __fd_glob_62 from "../content/docs/(root)/index.mdx?collection=docs"
import * as __fd_glob_61 from "../content/docs/(root)/get-started.mdx?collection=docs"
import * as __fd_glob_60 from "../content/docs/components/tooltip.mdx?collection=docs"
import * as __fd_glob_59 from "../content/docs/components/toolbar.mdx?collection=docs"
import * as __fd_glob_58 from "../content/docs/components/toggle.mdx?collection=docs"
import * as __fd_glob_57 from "../content/docs/components/toggle-group.mdx?collection=docs"
import * as __fd_glob_56 from "../content/docs/components/toast.mdx?collection=docs"
import * as __fd_glob_55 from "../content/docs/components/textarea.mdx?collection=docs"
import * as __fd_glob_54 from "../content/docs/components/tag.mdx?collection=docs"
import * as __fd_glob_53 from "../content/docs/components/tabs.mdx?collection=docs"
import * as __fd_glob_52 from "../content/docs/components/table.mdx?collection=docs"
import * as __fd_glob_51 from "../content/docs/components/switch.mdx?collection=docs"
import * as __fd_glob_50 from "../content/docs/components/status-badge.mdx?collection=docs"
import * as __fd_glob_49 from "../content/docs/components/spinner.mdx?collection=docs"
import * as __fd_glob_48 from "../content/docs/components/slider.mdx?collection=docs"
import * as __fd_glob_47 from "../content/docs/components/skeleton.mdx?collection=docs"
import * as __fd_glob_46 from "../content/docs/components/sheet.mdx?collection=docs"
import * as __fd_glob_45 from "../content/docs/components/separator.mdx?collection=docs"
import * as __fd_glob_44 from "../content/docs/components/select.mdx?collection=docs"
import * as __fd_glob_43 from "../content/docs/components/scroll-area.mdx?collection=docs"
import * as __fd_glob_42 from "../content/docs/components/rating-review.mdx?collection=docs"
import * as __fd_glob_41 from "../content/docs/components/rating-bar.mdx?collection=docs"
import * as __fd_glob_40 from "../content/docs/components/radio.mdx?collection=docs"
import * as __fd_glob_39 from "../content/docs/components/progress.mdx?collection=docs"
import * as __fd_glob_38 from "../content/docs/components/preview-card.mdx?collection=docs"
import * as __fd_glob_37 from "../content/docs/components/popover.mdx?collection=docs"
import * as __fd_glob_36 from "../content/docs/components/pagination.mdx?collection=docs"
import * as __fd_glob_35 from "../content/docs/components/number-field.mdx?collection=docs"
import * as __fd_glob_34 from "../content/docs/components/navigation-menu.mdx?collection=docs"
import * as __fd_glob_33 from "../content/docs/components/menu-bar.mdx?collection=docs"
import * as __fd_glob_32 from "../content/docs/components/link-button.mdx?collection=docs"
import * as __fd_glob_31 from "../content/docs/components/kbd.mdx?collection=docs"
import * as __fd_glob_30 from "../content/docs/components/input.mdx?collection=docs"
import * as __fd_glob_29 from "../content/docs/components/input-group.mdx?collection=docs"
import * as __fd_glob_28 from "../content/docs/components/field.mdx?collection=docs"
import * as __fd_glob_27 from "../content/docs/components/dropdown-menu.mdx?collection=docs"
import * as __fd_glob_26 from "../content/docs/components/drawer.mdx?collection=docs"
import * as __fd_glob_25 from "../content/docs/components/dialog.mdx?collection=docs"
import * as __fd_glob_24 from "../content/docs/components/context-menu.mdx?collection=docs"
import * as __fd_glob_23 from "../content/docs/components/command.mdx?collection=docs"
import * as __fd_glob_22 from "../content/docs/components/combobox.mdx?collection=docs"
import * as __fd_glob_21 from "../content/docs/components/collapsible.mdx?collection=docs"
import * as __fd_glob_20 from "../content/docs/components/checkbox.mdx?collection=docs"
import * as __fd_glob_19 from "../content/docs/components/checkbox-group.mdx?collection=docs"
import * as __fd_glob_18 from "../content/docs/components/button.mdx?collection=docs"
import * as __fd_glob_17 from "../content/docs/components/button-group.mdx?collection=docs"
import * as __fd_glob_16 from "../content/docs/components/breadcrumb.mdx?collection=docs"
import * as __fd_glob_15 from "../content/docs/components/banner.mdx?collection=docs"
import * as __fd_glob_14 from "../content/docs/components/badge.mdx?collection=docs"
import * as __fd_glob_13 from "../content/docs/components/avatar.mdx?collection=docs"
import * as __fd_glob_12 from "../content/docs/components/autocomplete.mdx?collection=docs"
import * as __fd_glob_11 from "../content/docs/components/alert.mdx?collection=docs"
import * as __fd_glob_10 from "../content/docs/components/alert-dialog.mdx?collection=docs"
import * as __fd_glob_9 from "../content/docs/components/accordion.mdx?collection=docs"
import * as __fd_glob_8 from "../content/docs/handbook/typography.mdx?collection=docs"
import * as __fd_glob_7 from "../content/docs/handbook/tokens.mdx?collection=docs"
import * as __fd_glob_6 from "../content/docs/handbook/styling.mdx?collection=docs"
import * as __fd_glob_5 from "../content/docs/handbook/colors.mdx?collection=docs"
import { default as __fd_glob_4 } from "../content/docs/resources/meta.json?collection=docs"
import { default as __fd_glob_3 } from "../content/docs/handbook/meta.json?collection=docs"
import { default as __fd_glob_2 } from "../content/docs/components/meta.json?collection=docs"
import { default as __fd_glob_1 } from "../content/docs/(root)/meta.json?collection=docs"
import { default as __fd_glob_0 } from "../content/docs/meta.json?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const docs = await create.docs("docs", "content/docs", {"meta.json": __fd_glob_0, "(root)/meta.json": __fd_glob_1, "components/meta.json": __fd_glob_2, "handbook/meta.json": __fd_glob_3, "resources/meta.json": __fd_glob_4, }, {"handbook/colors.mdx": __fd_glob_5, "handbook/styling.mdx": __fd_glob_6, "handbook/tokens.mdx": __fd_glob_7, "handbook/typography.mdx": __fd_glob_8, "components/accordion.mdx": __fd_glob_9, "components/alert-dialog.mdx": __fd_glob_10, "components/alert.mdx": __fd_glob_11, "components/autocomplete.mdx": __fd_glob_12, "components/avatar.mdx": __fd_glob_13, "components/badge.mdx": __fd_glob_14, "components/banner.mdx": __fd_glob_15, "components/breadcrumb.mdx": __fd_glob_16, "components/button-group.mdx": __fd_glob_17, "components/button.mdx": __fd_glob_18, "components/checkbox-group.mdx": __fd_glob_19, "components/checkbox.mdx": __fd_glob_20, "components/collapsible.mdx": __fd_glob_21, "components/combobox.mdx": __fd_glob_22, "components/command.mdx": __fd_glob_23, "components/context-menu.mdx": __fd_glob_24, "components/dialog.mdx": __fd_glob_25, "components/drawer.mdx": __fd_glob_26, "components/dropdown-menu.mdx": __fd_glob_27, "components/field.mdx": __fd_glob_28, "components/input-group.mdx": __fd_glob_29, "components/input.mdx": __fd_glob_30, "components/kbd.mdx": __fd_glob_31, "components/link-button.mdx": __fd_glob_32, "components/menu-bar.mdx": __fd_glob_33, "components/navigation-menu.mdx": __fd_glob_34, "components/number-field.mdx": __fd_glob_35, "components/pagination.mdx": __fd_glob_36, "components/popover.mdx": __fd_glob_37, "components/preview-card.mdx": __fd_glob_38, "components/progress.mdx": __fd_glob_39, "components/radio.mdx": __fd_glob_40, "components/rating-bar.mdx": __fd_glob_41, "components/rating-review.mdx": __fd_glob_42, "components/scroll-area.mdx": __fd_glob_43, "components/select.mdx": __fd_glob_44, "components/separator.mdx": __fd_glob_45, "components/sheet.mdx": __fd_glob_46, "components/skeleton.mdx": __fd_glob_47, "components/slider.mdx": __fd_glob_48, "components/spinner.mdx": __fd_glob_49, "components/status-badge.mdx": __fd_glob_50, "components/switch.mdx": __fd_glob_51, "components/table.mdx": __fd_glob_52, "components/tabs.mdx": __fd_glob_53, "components/tag.mdx": __fd_glob_54, "components/textarea.mdx": __fd_glob_55, "components/toast.mdx": __fd_glob_56, "components/toggle-group.mdx": __fd_glob_57, "components/toggle.mdx": __fd_glob_58, "components/toolbar.mdx": __fd_glob_59, "components/tooltip.mdx": __fd_glob_60, "(root)/get-started.mdx": __fd_glob_61, "(root)/index.mdx": __fd_glob_62, "(root)/roadmap.mdx": __fd_glob_63, });