// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

export const Index: Record<string, any> = {
  avatar: {
    name: "avatar",
    description: "An image element with a fallback for representing the user.",
    type: "registry:ui",
    registryDependencies: undefined,
    dependencies: ["@base-ui/react"],
    files: [
      {
        path: "@olyx/react/avatar/index.tsx",
        type: "registry:ui",
        target: "",
      },
      {
        path: "@olyx/react/avatar/style.css",
        type: "registry:style",
        target: "",
      },
    ],
    meta: { category: "core", tags: ["user", "profile", "image"] },
  },
  badge: {
    name: "badge",
    description: "Displays a badge or a component that looks like a badge.",
    type: "registry:ui",
    registryDependencies: undefined,
    dependencies: undefined,
    files: [
      {
        path: "@olyx/react/badge/index.tsx",
        type: "registry:ui",
        target: "",
      },
      {
        path: "@olyx/react/badge/style.css",
        type: "registry:style",
        target: "",
      },
    ],
    meta: { category: "core", tags: ["status", "label", "tag"] },
  },
  button: {
    name: "button",
    description: "Displays a button or a component that looks like a button.",
    type: "registry:ui",
    registryDependencies: undefined,
    dependencies: ["@base-ui/react"],
    files: [
      {
        path: "@olyx/react/button/index.tsx",
        type: "registry:ui",
        target: "",
      },
      {
        path: "@olyx/react/button/style.css",
        type: "registry:style",
        target: "",
      },
    ],
    meta: { category: "core", tags: ["action", "click", "primary"] },
  },
  "button-group": {
    name: "button-group",
    description: "Groups related buttons together.",
    type: "registry:ui",
    registryDependencies: ["button"],
    dependencies: undefined,
    files: [
      {
        path: "@olyx/react/button-group/index.tsx",
        type: "registry:ui",
        target: "",
      },
      {
        path: "@olyx/react/button-group/style.css",
        type: "registry:style",
        target: "",
      },
    ],
    meta: { category: "core", tags: ["group", "collection"] },
  },
  "scroll-area": {
    name: "scroll-area",
    description:
      "Augments native scroll functionality for custom, cross-browser styling.",
    type: "registry:ui",
    registryDependencies: undefined,
    dependencies: ["@base-ui/react"],
    files: [
      {
        path: "@olyx/react/scroll-area/index.tsx",
        type: "registry:ui",
        target: "",
      },
      {
        path: "@olyx/react/scroll-area/style.css",
        type: "registry:style",
        target: "",
      },
    ],
    meta: { category: "core", tags: ["scroll", "overflow"] },
  },
  separator: {
    name: "separator",
    description: "Visually or semantically separates content.",
    type: "registry:ui",
    registryDependencies: undefined,
    dependencies: ["@base-ui/react"],
    files: [
      {
        path: "@olyx/react/separator/index.tsx",
        type: "registry:ui",
        target: "",
      },
      {
        path: "@olyx/react/separator/style.css",
        type: "registry:style",
        target: "",
      },
    ],
    meta: { category: "core", tags: ["divider", "hr"] },
  },
  "status-badge": {
    name: "status-badge",
    description: "Displays status information with colored indicators.",
    type: "registry:ui",
    registryDependencies: undefined,
    dependencies: undefined,
    files: [
      {
        path: "@olyx/react/status-badge/index.tsx",
        type: "registry:ui",
        target: "",
      },
      {
        path: "@olyx/react/status-badge/style.css",
        type: "registry:style",
        target: "",
      },
    ],
    meta: { category: "core", tags: ["status", "indicator"] },
  },
  banner: {
    name: "banner",
    description: "A prominent message display at the top of the page.",
    type: "registry:ui",
    registryDependencies: ["button"],
    dependencies: undefined,
    files: [
      {
        path: "@olyx/react/banner/index.tsx",
        type: "registry:ui",
        target: "",
      },
      {
        path: "@olyx/react/banner/style.css",
        type: "registry:style",
        target: "",
      },
    ],
    meta: { category: "data-display", tags: ["announcement", "message"] },
  },
  kbd: {
    name: "kbd",
    description:
      "Displays which key or combination of keys performs a given action.",
    type: "registry:ui",
    registryDependencies: undefined,
    dependencies: undefined,
    files: [
      {
        path: "@olyx/react/kbd/index.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    meta: { category: "data-display", tags: ["keyboard", "shortcut"] },
  },
  progress: {
    name: "progress",
    description:
      "Displays an indicator showing the completion progress of a task.",
    type: "registry:ui",
    registryDependencies: undefined,
    dependencies: ["@base-ui/react"],
    files: [
      {
        path: "@olyx/react/progress/index.tsx",
        type: "registry:ui",
        target: "",
      },
      {
        path: "@olyx/react/progress/style.css",
        type: "registry:style",
        target: "",
      },
    ],
    meta: { category: "data-display", tags: ["loading", "indicator"] },
  },
  "rating-bar": {
    name: "rating-bar",
    description: "Displays a rating using stars or other indicators.",
    type: "registry:ui",
    registryDependencies: ["radio"],
    dependencies: undefined,
    files: [
      {
        path: "@olyx/react/rating-bar/index.tsx",
        type: "registry:ui",
        target: "",
      },
      {
        path: "@olyx/react/rating-bar/style.css",
        type: "registry:style",
        target: "",
      },
    ],
    meta: { category: "data-display", tags: ["rating", "stars"] },
  },
  "rating-review": {
    name: "rating-review",
    description: "Displays detailed rating information with reviews.",
    type: "registry:ui",
    registryDependencies: undefined,
    dependencies: undefined,
    files: [
      {
        path: "@olyx/react/rating-review/index.tsx",
        type: "registry:ui",
        target: "",
      },
      {
        path: "@olyx/react/rating-review/style.css",
        type: "registry:style",
        target: "",
      },
    ],
    meta: { category: "data-display", tags: ["rating", "review"] },
  },
  table: {
    name: "table",
    description: "A responsive table component for displaying tabular data.",
    type: "registry:ui",
    registryDependencies: undefined,
    dependencies: undefined,
    files: [
      {
        path: "@olyx/react/table/index.tsx",
        type: "registry:ui",
        target: "",
      },
      {
        path: "@olyx/react/table/style.css",
        type: "registry:style",
        target: "",
      },
    ],
    meta: { category: "data-display", tags: ["data", "grid"] },
  },
  tag: {
    name: "tag",
    description:
      "A compact element that represents an input, attribute, or action.",
    type: "registry:ui",
    registryDependencies: undefined,
    dependencies: undefined,
    files: [
      {
        path: "@olyx/react/tag/index.tsx",
        type: "registry:ui",
        target: "",
      },
      {
        path: "@olyx/react/tag/style.css",
        type: "registry:style",
        target: "",
      },
    ],
    meta: { category: "data-display", tags: ["label", "chip"] },
  },
  accordion: {
    name: "accordion",
    description:
      "A vertically stacked set of interactive headings that each reveal a section of content.",
    type: "registry:ui",
    registryDependencies: undefined,
    dependencies: ["@base-ui/react"],
    files: [
      {
        path: "@olyx/react/accordion/index.tsx",
        type: "registry:ui",
        target: "",
      },
      {
        path: "@olyx/react/accordion/style.css",
        type: "registry:style",
        target: "",
      },
    ],
    meta: { category: "disclosure", tags: ["collapsible", "expandable"] },
  },
  collapsible: {
    name: "collapsible",
    description: "An interactive component which expands/collapses a panel.",
    type: "registry:ui",
    registryDependencies: undefined,
    dependencies: ["@base-ui/react"],
    files: [
      {
        path: "@olyx/react/collapsible/index.tsx",
        type: "registry:ui",
        target: "",
      },
      {
        path: "@olyx/react/collapsible/style.css",
        type: "registry:style",
        target: "",
      },
    ],
    meta: { category: "disclosure", tags: ["expand", "collapse"] },
  },
  "context-menu": {
    name: "context-menu",
    description:
      "Displays a menu to the user — such as a set of actions or functions — triggered by a button.",
    type: "registry:ui",
    registryDependencies: undefined,
    dependencies: ["@base-ui/react"],
    files: [
      {
        path: "@olyx/react/context-menu/index.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    meta: { category: "disclosure", tags: ["menu", "right-click"] },
  },
  drawer: {
    name: "drawer",
    description: "A drawer component for React.",
    type: "registry:ui",
    registryDependencies: undefined,
    dependencies: ["@base-ui/react"],
    files: [
      {
        path: "@olyx/react/drawer/index.tsx",
        type: "registry:ui",
        target: "",
      },
      {
        path: "@olyx/react/drawer/style.css",
        type: "registry:style",
        target: "",
      },
    ],
    meta: { category: "disclosure", tags: ["sheet", "slide"] },
  },
  "dropdown-menu": {
    name: "dropdown-menu",
    description:
      "Displays a menu to the user — such as a set of actions or functions — triggered by a button.",
    type: "registry:ui",
    registryDependencies: undefined,
    dependencies: ["@base-ui/react"],
    files: [
      {
        path: "@olyx/react/dropdown-menu/index.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    meta: { category: "disclosure", tags: ["menu", "dropdown"] },
  },
  "menu-bar": {
    name: "menu-bar",
    description: "A visually persistent menu common in desktop applications.",
    type: "registry:ui",
    registryDependencies: undefined,
    dependencies: ["@base-ui/react"],
    files: [
      {
        path: "@olyx/react/menu-bar/index.tsx",
        type: "registry:ui",
        target: "",
      },
      {
        path: "@olyx/react/menu-bar/style.css",
        type: "registry:style",
        target: "",
      },
    ],
    meta: { category: "disclosure", tags: ["menubar", "desktop"] },
  },
  popover: {
    name: "popover",
    description: "Displays rich content in a portal, triggered by a button.",
    type: "registry:ui",
    registryDependencies: undefined,
    dependencies: ["@base-ui/react"],
    files: [
      {
        path: "@olyx/react/popover/index.tsx",
        type: "registry:ui",
        target: "",
      },
      {
        path: "@olyx/react/popover/style.css",
        type: "registry:style",
        target: "",
      },
    ],
    meta: { category: "disclosure", tags: ["popup", "overlay"] },
  },
  alert: {
    name: "alert",
    description: "Displays a callout for user attention.",
    type: "registry:ui",
    registryDependencies: undefined,
    dependencies: undefined,
    files: [
      {
        path: "@olyx/react/alert/index.tsx",
        type: "registry:ui",
        target: "",
      },
      {
        path: "@olyx/react/alert/style.css",
        type: "registry:style",
        target: "",
      },
    ],
    meta: { category: "feedback", tags: ["callout", "notification"] },
  },
  "alert-dialog": {
    name: "alert-dialog",
    description:
      "A modal dialog that interrupts the user with important content and expects a response.",
    type: "registry:ui",
    registryDependencies: ["button"],
    dependencies: ["@base-ui/react"],
    files: [
      {
        path: "@olyx/react/alert-dialog/index.tsx",
        type: "registry:ui",
        target: "",
      },
      {
        path: "@olyx/react/alert-dialog/style.css",
        type: "registry:style",
        target: "",
      },
    ],
    meta: { category: "feedback", tags: ["modal", "confirm"] },
  },
  dialog: {
    name: "dialog",
    description:
      "A window overlaid on either the primary window or another dialog window, rendering the content underneath inert.",
    type: "registry:ui",
    registryDependencies: undefined,
    dependencies: ["@base-ui/react"],
    files: [
      {
        path: "@olyx/react/dialog/index.tsx",
        type: "registry:ui",
        target: "",
      },
      {
        path: "@olyx/react/dialog/style.css",
        type: "registry:style",
        target: "",
      },
    ],
    meta: { category: "feedback", tags: ["modal", "overlay"] },
  },
  "preview-card": {
    name: "preview-card",
    description: "A card that displays a preview of content with actions.",
    type: "registry:ui",
    registryDependencies: ["button"],
    dependencies: undefined,
    files: [
      {
        path: "@olyx/react/preview-card/index.tsx",
        type: "registry:ui",
        target: "",
      },
      {
        path: "@olyx/react/preview-card/style.css",
        type: "registry:style",
        target: "",
      },
    ],
    meta: { category: "feedback", tags: ["preview", "card"] },
  },
  spinner: {
    name: "spinner",
    description: "A loading indicator that spins to indicate progress.",
    type: "registry:ui",
    registryDependencies: undefined,
    dependencies: undefined,
    files: [
      {
        path: "@olyx/react/spinner/index.tsx",
        type: "registry:ui",
        target: "",
      },
      {
        path: "@olyx/react/spinner/style.css",
        type: "registry:style",
        target: "",
      },
    ],
    meta: { category: "feedback", tags: ["loading", "progress"] },
  },
  toast: {
    name: "toast",
    description: "A succinct message that is displayed temporarily.",
    type: "registry:ui",
    registryDependencies: undefined,
    dependencies: ["@base-ui/react"],
    files: [
      {
        path: "@olyx/react/toast/index.tsx",
        type: "registry:ui",
        target: "",
      },
      {
        path: "@olyx/react/toast/style.css",
        type: "registry:style",
        target: "",
      },
    ],
    meta: { category: "feedback", tags: ["notification", "snackbar"] },
  },
  tooltip: {
    name: "tooltip",
    description:
      "A popup that displays information related to an element when the element receives keyboard focus or the mouse hovers over it.",
    type: "registry:ui",
    registryDependencies: undefined,
    dependencies: ["@base-ui/react"],
    files: [
      {
        path: "@olyx/react/tooltip/index.tsx",
        type: "registry:ui",
        target: "",
      },
      {
        path: "@olyx/react/tooltip/style.css",
        type: "registry:style",
        target: "",
      },
    ],
    meta: { category: "feedback", tags: ["hint", "popup"] },
  },
  checkbox: {
    name: "checkbox",
    description:
      "A control that allows the user to toggle between checked and not checked.",
    type: "registry:ui",
    registryDependencies: undefined,
    dependencies: ["@base-ui/react"],
    files: [
      {
        path: "@olyx/react/checkbox/index.tsx",
        type: "registry:ui",
        target: "",
      },
      {
        path: "@olyx/react/checkbox/style.css",
        type: "registry:style",
        target: "",
      },
    ],
    meta: { category: "form", tags: ["input", "boolean", "toggle"] },
  },
  combobox: {
    name: "combobox",
    description:
      "Autocomplete input and command palette with a list of suggestions.",
    type: "registry:ui",
    registryDependencies: undefined,
    dependencies: ["@base-ui/react"],
    files: [
      {
        path: "@olyx/react/combobox/index.tsx",
        type: "registry:ui",
        target: "",
      },
      {
        path: "@olyx/react/combobox/style.css",
        type: "registry:style",
        target: "",
      },
    ],
    meta: { category: "form", tags: ["autocomplete", "search", "select"] },
  },
  field: {
    name: "field",
    description: "A form field with label, input, and error message.",
    type: "registry:ui",
    registryDependencies: ["input"],
    dependencies: undefined,
    files: [
      {
        path: "@olyx/react/field/index.tsx",
        type: "registry:ui",
        target: "",
      },
      {
        path: "@olyx/react/field/style.css",
        type: "registry:style",
        target: "",
      },
    ],
    meta: { category: "form", tags: ["wrapper", "label", "error"] },
  },
  input: {
    name: "input",
    description:
      "Displays a form input field or a component that looks like an input field.",
    type: "registry:ui",
    registryDependencies: undefined,
    dependencies: undefined,
    files: [
      {
        path: "@olyx/react/input/index.tsx",
        type: "registry:ui",
        target: "",
      },
      {
        path: "@olyx/react/input/style.css",
        type: "registry:style",
        target: "",
      },
    ],
    meta: { category: "form", tags: ["text", "field"] },
  },
  "number-field": {
    name: "number-field",
    description: "A numeric input with increment and decrement buttons.",
    type: "registry:ui",
    registryDependencies: undefined,
    dependencies: ["@base-ui/react"],
    files: [
      {
        path: "@olyx/react/number-field/index.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    meta: { category: "form", tags: ["numeric", "stepper"] },
  },
  radio: {
    name: "radio",
    description:
      "A set of checkable buttons—known as radio buttons—where no more than one of the buttons can be checked at a time.",
    type: "registry:ui",
    registryDependencies: undefined,
    dependencies: ["@base-ui/react"],
    files: [
      {
        path: "@olyx/react/radio/index.tsx",
        type: "registry:ui",
        target: "",
      },
      {
        path: "@olyx/react/radio/style.css",
        type: "registry:style",
        target: "",
      },
    ],
    meta: { category: "form", tags: ["choice", "option", "group"] },
  },
  select: {
    name: "select",
    description:
      "Displays a list of options for the user to pick from—triggered by a button.",
    type: "registry:ui",
    registryDependencies: undefined,
    dependencies: ["@base-ui/react"],
    files: [
      {
        path: "@olyx/react/select/index.tsx",
        type: "registry:ui",
        target: "",
      },
      {
        path: "@olyx/react/select/style.css",
        type: "registry:style",
        target: "",
      },
    ],
    meta: { category: "form", tags: ["dropdown", "picker"] },
  },
  slider: {
    name: "slider",
    description:
      "An input where the user selects a value from within a given range.",
    type: "registry:ui",
    registryDependencies: undefined,
    dependencies: ["@base-ui/react"],
    files: [
      {
        path: "@olyx/react/slider/index.tsx",
        type: "registry:ui",
        target: "",
      },
      {
        path: "@olyx/react/slider/style.css",
        type: "registry:style",
        target: "",
      },
    ],
    meta: { category: "form", tags: ["range", "input"] },
  },
  switch: {
    name: "switch",
    description:
      "A control that allows the user to toggle between checked and not checked.",
    type: "registry:ui",
    registryDependencies: undefined,
    dependencies: ["@base-ui/react"],
    files: [
      {
        path: "@olyx/react/switch/index.tsx",
        type: "registry:ui",
        target: "",
      },
      {
        path: "@olyx/react/switch/style.css",
        type: "registry:style",
        target: "",
      },
    ],
    meta: { category: "form", tags: ["toggle", "boolean"] },
  },
  textarea: {
    name: "textarea",
    description:
      "Displays a form textarea or a component that looks like a textarea.",
    type: "registry:ui",
    registryDependencies: undefined,
    dependencies: undefined,
    files: [
      {
        path: "@olyx/react/textarea/index.tsx",
        type: "registry:ui",
        target: "",
      },
      {
        path: "@olyx/react/textarea/style.css",
        type: "registry:style",
        target: "",
      },
    ],
    meta: { category: "form", tags: ["multiline", "text"] },
  },
  toggle: {
    name: "toggle",
    description: "A two-state button that can be either on or off.",
    type: "registry:ui",
    registryDependencies: undefined,
    dependencies: ["@base-ui/react"],
    files: [
      {
        path: "@olyx/react/toggle/index.tsx",
        type: "registry:ui",
        target: "",
      },
      {
        path: "@olyx/react/toggle/style.css",
        type: "registry:style",
        target: "",
      },
    ],
    meta: { category: "form", tags: ["button", "state"] },
  },
  skeleton: {
    name: "skeleton",
    description: "Use to show a placeholder while content is loading.",
    type: "registry:ui",
    registryDependencies: undefined,
    dependencies: undefined,
    files: [
      {
        path: "@olyx/react/skeleton/index.tsx",
        type: "registry:ui",
        target: "",
      },
      {
        path: "@olyx/react/skeleton/style.css",
        type: "registry:style",
        target: "",
      },
    ],
    meta: { category: "layout", tags: ["loading", "placeholder"] },
  },
  breadcrumb: {
    name: "breadcrumb",
    description:
      "Displays the path to the current resource using a hierarchy of links.",
    type: "registry:ui",
    registryDependencies: undefined,
    dependencies: undefined,
    files: [
      {
        path: "@olyx/react/breadcrumb/index.tsx",
        type: "registry:ui",
        target: "",
      },
      {
        path: "@olyx/react/breadcrumb/style.css",
        type: "registry:style",
        target: "",
      },
    ],
    meta: { category: "navigation", tags: ["breadcrumbs", "path"] },
  },
  "navigation-menu": {
    name: "navigation-menu",
    description: "A collection of links for navigating websites.",
    type: "registry:ui",
    registryDependencies: undefined,
    dependencies: ["@base-ui/react"],
    files: [
      {
        path: "@olyx/react/navigation-menu/index.tsx",
        type: "registry:ui",
        target: "",
      },
      {
        path: "@olyx/react/navigation-menu/style.css",
        type: "registry:style",
        target: "",
      },
    ],
    meta: { category: "navigation", tags: ["menu", "navigation"] },
  },
  pagination: {
    name: "pagination",
    description: "Pagination with page navigation, next and previous links.",
    type: "registry:ui",
    registryDependencies: ["button"],
    dependencies: undefined,
    files: [
      {
        path: "@olyx/react/pagination/index.tsx",
        type: "registry:ui",
        target: "",
      },
      {
        path: "@olyx/react/pagination/style.css",
        type: "registry:style",
        target: "",
      },
    ],
    meta: { category: "navigation", tags: ["paging", "pages"] },
  },
  tabs: {
    name: "tabs",
    description:
      "A set of layered sections of content—known as tab panels—that are displayed one at a time.",
    type: "registry:ui",
    registryDependencies: undefined,
    dependencies: ["@base-ui/react"],
    files: [
      {
        path: "@olyx/react/tabs/index.tsx",
        type: "registry:ui",
        target: "",
      },
      {
        path: "@olyx/react/tabs/style.css",
        type: "registry:style",
        target: "",
      },
    ],
    meta: { category: "navigation", tags: ["tabpanel", "switcher"] },
  },
  toolbar: {
    name: "toolbar",
    description: "A container for grouping a set of controls.",
    type: "registry:ui",
    registryDependencies: ["button"],
    dependencies: ["@base-ui/react"],
    files: [
      {
        path: "@olyx/react/toolbar/index.tsx",
        type: "registry:ui",
        target: "",
      },
      {
        path: "@olyx/react/toolbar/style.css",
        type: "registry:style",
        target: "",
      },
    ],
    meta: { category: "navigation", tags: ["controls", "actions"] },
  },
};
