import { promises as fs } from "node:fs";
import path from "node:path";
import { registry } from "../src/registry/index.js";

const ROOT = process.cwd();

async function buildRegistryIndex() {
  let index = `// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

export const Index: Record<string, any> = {`;

  for (const item of registry.items) {
    if (!item.files?.length) continue;

    index += `
  "${item.name}": {
    name: "${item.name}",
    description: "${item.description ?? ""}",
    type: "${item.type}",
    registryDependencies: ${JSON.stringify(item.registryDependencies)},
    dependencies: ${JSON.stringify(item.dependencies)},
    files: [${item.files
      .map(
        (file) => `{
      path: "${file.path}",
      type: "${file.type}",
      target: "${file.target ?? ""}"
    }`,
      )
      .join(", ")}],
    meta: ${JSON.stringify(item.meta)},
  },`;
  }

  index += `
}
`;

  await fs.writeFile(path.join(ROOT, "src/registry/__index__.ts"), index);

  console.log(`✅ Built __index__.ts with ${registry.items.length} items`);
}

async function buildRegistryJson() {
  const fixedRegistry = {
    ...registry,
    items: registry.items.map((item) => ({
      ...item,
      files: item.files?.map((file) => ({
        ...file,
        path: file.path.replace("@olyx/react/", "ui/"),
      })),
    })),
  };

  await fs.writeFile(
    path.join(ROOT, "registry.json"),
    JSON.stringify(fixedRegistry, null, 2),
  );

  console.log("✅ Built registry.json");
}

try {
  console.log("🏗️  Building registry...");
  await buildRegistryIndex();
  await buildRegistryJson();
  console.log("🎉 Done!");
} catch (error) {
  console.error("❌ Build failed:", error);
  process.exit(1);
}
